from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from smart_charging_optimization_engine.domain.jobs import OptimizationJob
    from smart_charging_optimization_engine.domain.models import (
        ChargingScenario,
        PortfolioScenario,
        TelemetrySnapshot,
    )
    from smart_charging_optimization_engine.domain.results import (
        MultiSiteOptimizationResult,
        OptimizationResult,
    )
    from smart_charging_optimization_engine.domain.runs import OptimizationRun


class StateRepository(Protocol):
    def save_scenario(self, scenario_id: str, scenario: ChargingScenario) -> str: ...

    def load_scenario(self, scenario_id: str) -> ChargingScenario: ...

    def list_scenarios(self) -> list[str]: ...

    def count_scenarios(self) -> int: ...

    def save_portfolio(self, scenario_id: str, scenario: PortfolioScenario) -> str: ...

    def load_portfolio(self, scenario_id: str) -> PortfolioScenario: ...

    def save_telemetry(self, snapshot_id: str, telemetry: TelemetrySnapshot) -> str: ...

    def load_telemetry(self, snapshot_id: str) -> TelemetrySnapshot: ...

    def save_result(self, result_id: str, result: OptimizationResult) -> str: ...

    def load_result(self, result_id: str) -> OptimizationResult: ...

    def save_multisite_result(
        self,
        result_id: str,
        result: MultiSiteOptimizationResult,
    ) -> str: ...

    def load_multisite_result(self, result_id: str) -> MultiSiteOptimizationResult: ...

    def save_run(self, run_id: str, run: OptimizationRun) -> str: ...

    def load_run(self, run_id: str) -> OptimizationRun: ...

    def list_runs(self) -> list[str]: ...

    def count_runs(self) -> int: ...

    def save_job(self, job_id: str, job: OptimizationJob) -> str: ...

    def load_job(self, job_id: str) -> OptimizationJob: ...

    def list_jobs(self) -> list[str]: ...

    def count_jobs(self) -> int: ...

    def load_all_jobs(self) -> list[OptimizationJob]: ...

    def count_pending_jobs(self) -> int: ...

    def load_all_runs(self) -> list[OptimizationRun]: ...

    def save_job_input(self, job_id: str, payload: dict[str, Any]) -> str: ...

    def load_job_input(self, job_id: str) -> dict[str, Any]: ...

    def delete_run(self, run_id: str) -> None: ...

    def delete_job(self, job_id: str) -> None: ...

    def close(self) -> None: ...
